version: "3.9"

services:
  app:
    build: .
    container_name: malicious_text_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - NLTK_DATA=/usr/local/share/nltk_data
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  es_data:
